### ISSUE TITLE
does not support iPhone X properly

### ISSUE THREAD

**Issue by 5tigerjelly** [pass-n-play/pass-n-play#28]
![img_2967](https://user-images.githubusercontent.com/15973528/40896641-04420b60-676b-11e8-9dde-80b0f35be90e.JPG)

**Comment by campbellsean** [comment]
@samsturtevant we need more padding

**Comment by samsturtevant** [comment]
@campbellsean and more padding you will get

**Comment by campbellsean** [comment]
@samsturtevant added padding this issue is now closed
