### ISSUE TITLE
Missing on/off slider?

### ISSUE THREAD

**Issue by harrybarng** [pass-n-play/pass-n-play#32]
the requirement states there should be an ability to have on/off slider for edit prompt but I was not able to find one. Perhaps it is hidden? Or deployment is messed up?

**Comment by campbellsean** [comment]
I do not think I fully understand this issue. For each individual prompt you do have the ability to turn it off by clicking the red X or scrolling to off.

However we did not find use in turning off whole categories of prompts as it would limit the game play and cause errors in the way custom play worked. For example, if you turn off Custom Play prompts, but then play a custom play game then the user would be upset that the game isn't "custom."

**Comment by harrybarng** [comment]
I raised the question because your  requirement said there would be an "on
and off slider" that would allow the user to turn off the whole category
but I was not able to use that and was forced to turn off everything one by
one manually
