### ISSUE TITLE
Although I clicked on discard button it still saves the information

### ISSUE THREAD

**Issue by juan3674-1532739** [pass-n-play/pass-n-play#33]
So, I tried to make a custom add prompt and add some prompt. But even though I clicked the back button and discard changes. It still saved the discarded changes. Not even for the making prompt but also I changed the value to med to high and I tried to discard the change, but it still saves the discarded change.

**Comment by JordanFreitas** [comment]
This was an issue with the extra save feature, removed this extra button and step when closing the area so problem should be fixed!
